### ISSUE TITLE
Less compilation slow in development mode

### ISSUE THREAD

**Issue by tirdadc** [maxd/less-rails-semantic_ui#4]
As much as I wanted to use this and not rely on the minified precompiled CSS dist files, the compilation cost makes using this approach too slow in development. I tried disabling unused Semantic components in both the CSS and JS files, and it was still pretty bad (1 - 2 seconds).

**Comment by maxd** [comment]
First time compilation and any changes in \*.overrides/\*.variables files takes about 10-20 seconds for compilation but this is very rare events. Other changes takes less than second because Sprockets using compiled resources from cache. So, I think this is acceptable delays. 

Are you sure that your delays related to periodical compilation of LESS files from less-rails-semantic_ui?

**Comment by tirdadc** [comment]
This was without any custom changes to the .overrides files with a classic Rails development configuration (which I can post here) and all of the modules included by default.

I don't know what the cause is exactly but I had to switch to https://github.com/doabit/semantic-ui-sass because it didn't result in 1-2s page loads.

**Comment by robomc** [comment]
I'm having the same issue - development is *extremely* slow if there's any change in the /vendor folder.

**Comment by domi91c** [comment]
I'm having this problem as well.

**Comment by karanr** [comment]
I am facing this issue as well.
