### ISSUE TITLE
Automatic recompilation when modifying *.overrides or *.variables files in development

### ISSUE THREAD

**Issue by jorgemanrubia** [maxd/less-rails-semantic_ui#9]
Hi,

In development, after modifying `.overrides` or `.variables` files in `vendor/assets/stylesheets/semantic_ui`, I need to restart server and clear the assets cache in order to see the expected changes. 

I have tried a number of things to fix this and I was wondering if this is the expected behavior or if I am doing something wrong.

Thanks

Regards

**Comment by jorgemanrubia** [comment]
An update:

Interestingly, changing `@pageFont` will be picked up dynamically, but a color variable like `@blue` won't until restarting and clearing the cache.

(in `globals/site.variables`)

Regards

**Comment by maxd** [comment]
@jorgemanrubia I have added Sprockets dependencies to globals/*.{overrides,variable} files. It should fix your problem. Could you please get latest version from `master` and check it?

**Comment by jorgemanrubia** [comment]
Hi @maxd,

It works! Thank you so much for looking into it. 

Only thing I have noted is that when you modify the file it takes a lot of time to reload the app, due to recompiling everything, I imagine there is nothing to do on that front. In any case your solution works.

Thanks

**Comment by maxd** [comment]
Yes, you are right. Impossible to decrease compilation time because configuration files from `globals` directory included to all other *.less files. One way to decrease compilation time is use component specific `*.{overrides,variables}` files. In this case only changed components should be re-compilled.

FYI: I will try to release new gem version during a day.
